### ISSUE TITLE
Naming discussion

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#1]
DBMegaBot is the name of the repo and the group, but this is temporary as we agreed on. We need to come up with a proper name.

So far, Hubbe has suggested DesertBot, which I really like :P

**Comment by MaraKalat** [comment]
I'm definitely in favour of DesertBot as a name :+1:

**Comment by Heufneutje** [comment]
Name seems to be pretty widely agreed on. Waiting on @MatthewCox and then this issue can hopefully be closed.

**Comment by HubbeKing** [comment]
Tyranic-Moron is okay with it, let's go with DesertBot.
