### ISSUE TITLE
File architecture

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#10]
Follow-up of a discussion spawned in https://github.com/DesertBot/DesertBot/issues/5

I think moving bothandler out of the desertbus package is a bad idea because other modules will depend on it. The reason why I have start.py outside is because its only purpose is to parse the command line arguments and to start the bot. After that it shouldn't be needed anymore. I guess I kinda went ahead and did what I did with all my bots so far, which is to separate startup code from everything else since generally you only need it once and it doesn't need to be in classes that are used during runtime. Another reason why we have `start.py` is to ensure you're reading and writing files to the right folders and the code runs one folder level lower.

Another possibility would be to have start.py parse all the command line stuff and make it pass only the results to the bothandler rather than passing everything.

**Comment by HubbeKing** [comment]
The thing is, though, we do need the command args in order to restart the bot.

**Comment by Heufneutje** [comment]
Python remembers those. You don't need the parser arguments for that.

**Comment by StarlitGhost** [comment]
I agree with Heufy. The start script should be isolated as much as we can.
And yeah, you can access the command line arguments at any point, anywhere in the code.

**Comment by Heufneutje** [comment]
I think this has been agreed on so this issue can be closed.
