### ISSUE TITLE
DesertBot tries to reconnect when Z-lined or /KILLed

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#13]
Reconnecting is nice, but a client shouldn't be doing this normally. It's something Twisted does.

**Comment by Heufneutje** [comment]
I have kind of an idea on how to do this. The server sends us an ERROR command to let us know why the connection was closed. The only problem is that I can't think of a clean way to parse this ERROR line to determine when we should reconnect and when we should not.

**Comment by HubbeKing** [comment]
PyMoronBot does something similar for when he's reconnecting, the reconnect thing doesn't fire if the restarting flag is set, so if we can just detect a Z-line/KILL then we could just do something like that.

**Comment by ElementalAlchemist** [comment]
There's not really a consistent way to detect z:lines/g:lines/etc. across IRCds, so that might be a bit painful.  Maybe a reconnect attempt limit?

For kills, the client being killed receives a KILL command as part of the kill process (right before ERROR).

**Comment by HubbeKing** [comment]
So we can just parse the KILL command in a module and then log what happened and shutdown?

**Comment by ElementalAlchemist** [comment]
Yes (from InspIRCd):

> blah blah connection stuff with my test user
> :moonbase.ferwy.net 396 Alchy|Test Ferwy-8dko2f.tx.charter.com :is now your displayed host
> :Alchy|Test!Alchy@Ferwy-8dko2f.tx.charter.com MODE Alchy|Test +ix
> :ElementalAlchemist!Alchy@netadmin.ferwy.net KILL Alchy|Test :moonbase.ferwy.net!netadmin.ferwy.net!ElementalAlchemist (Killed (ElementalAlchemist (This is a test of the Emergency Alert System.)))
> ERROR :Closing link: (Alchy@68-187-65-179.dhcp.ftwo.tx.charter.com) [Killed (ElementalAlchemist (This is a test of the Emergency Alert System.))]
> Connection closed by foreign host.

**Comment by Heufneutje** [comment]
This issue no longer applies since we switched away from Twisted
