### ISSUE TITLE
Command line stuff for start.py

### ISSUE THREAD

**Issue by HubbeKing** [DesertBot/DesertBot-old#15]
We should decide if we're gonna stick with -s (--servers) even though it actually means the config file names. It's kinda unclear from the file itself and the description in the argParser.

**Comment by Heufneutje** [comment]
We could always do what I've done for RE_HeufyBot and PyHeufyBot and make it load every config in the folder. Or we could add a `connectOnStartup` setting to them.

**Comment by StarlitGhost** [comment]
or change it to -c (--configs)

**Comment by StarlitGhost** [comment]
Changed to -c (--configs) in 58dc8f9b88ed9bae8a42c60996b71b2cff9cd63b
