### ISSUE TITLE
Update module fails on long commit messages.

### ISSUE THREAD

**Issue by HubbeKing** [DesertBot/DesertBot-old#16]
This has been around ever since update was first made for PyMoronBot. I suspect the parsing of whatchanged is to blame...

I found a gist of someone elses solution for whatchanged parsing, perhaps we could draw ideas from it?
https://gist.github.com/dryan/3870152

**Comment by Heufneutje** [comment]
I've been meaning to look into the update module for a while now. I think I'll need to get a better understanding of the git commands we're using.

**Comment by HubbeKing** [comment]
It's mainly this one: http://git-scm.com/docs/git-whatchanged.html

Though apparently they recommend you use git log instead?

**Comment by Heufneutje** [comment]
I don't know too much about those commands, but I do know there is something we're doing wrong. We're executing `git fetch`, then check for changes and then `get pull`. If we're using `fetch`, we should be using `merge` to apply the changes, since `git pull` is `git fetch` and `git merge` in one operation.

**Comment by StarlitGhost** [comment]
We discussed it in chat, but:
`git log --no-merges --pretty=format:"%s %b" ..origin/master`
gives us exactly what we need for the commit messages.

We might also want to detect when a merge is blocked for some reason, ie some of the files that have changes have been edited locally.

Oh, and yes it should be changed from `git pull` to `git merge`.

**Comment by StarlitGhost** [comment]
This was fixed today between Hubbe and me.
