### ISSUE TITLE
Utility modules should not be displayed in the help command

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#18]
They should show up in a modules command though.

**Comment by HubbeKing** [comment]
Simplest way to do this is to have the help module get a list of all modules that aren't UTILITY for the !help command, and add a !modules command which would just list all modules.

**Comment by StarlitGhost** [comment]
Same with postprocess modules. Maybe passive ones too.

**Comment by HubbeKing** [comment]
The normal !help command already doesn't list postprocess commands, as it only gets a sorted list from the loadedModules dict. (it will, however, display help for postprocess modules if asked directly)

**Comment by StarlitGhost** [comment]
This is now done, only modules that have triggers will be listed by !help.
We also added !modules to list everything, and !commands <module> to list all the triggers provided by a given module.
