### ISSUE TITLE
[modules/admin] file creation logic never executes if there are no admins

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot-old#19]
The file creation doesn't work if there are no admins, as no one can use a command that would cause that code to execute (ie, unload the module directly, via shutdown, via restart, etc).

Perhaps if there are no admins it should default to allowing anyone?
Then when someone sets themselves as admin it would go to normal behaviour.

**Comment by Heufneutje** [comment]
:+1:
