### ISSUE TITLE
Persistent data storage and config file format

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#2]
We need to figure out how we're going to store data. Possible ideas are sqlite and or flat files (maybe JSON)

As for the configuration file, my vote is for YAML, as it's very easily readable, translates to a dictionary in Python and allows for comments.

**Comment by HubbeKing** [comment]
As much as I like SQL, JSON would probably be the most convinient.

**Comment by StarlitGhost** [comment]
I'm really liking using shelve for my persistent data as you just use it like you would any other dictionary, but the file it creates isn't human readable. If that's a concern then I suppose I'd vote for JSON.

For configuration I agree YAML is pretty much perfect.

**Comment by HubbeKing** [comment]
JSON for persistent data storage then, (in the unlikely but possible event we need to get some data and the bot/function is broken) And YAML for configs because YAML.
