### ISSUE TITLE
Admin modularity?

### ISSUE THREAD

**Issue by HubbeKing** [DesertBot/DesertBot-old#22]
I was thinking earlier about modularity and it struck me that all the admin stuff could fairly easily be made a module.

Just make a module with high priority check the accessLevel of modules against the same admin-list we have now, just move it all into a module.

You could then use a flag, similar to how we're thinking of making ignores, to make sure no further responses are generated from the message that's unauthorized. Or the .clear() idea we were thinking of earlier for IRCMessage.

**Comment by Heufneutje** [comment]
:+1:

**Comment by StarlitGhost** [comment]
Yeah, seems good.

I think this would only work for commands though? Not that I can imagine
any other kind of module being admin-only.

**Comment by HubbeKing** [comment]
Should we then make the checking of access its own module, or integrate that into the admin-module we already have? Kinda makes sense to have all the admin stuff in a single module, but it would have to be PASSIVE so it always triggers, but still check for the admin-list stuff manually in onTrigger.

**Comment by HubbeKing** [comment]
I'm thinking the access-level module would take in every message, much like log will, and check if the module that's supposed to trigger on it is admin-only, return an IRCResponse if so, and call .clear() on the message. But true, unless we give each module its own shouldTrigger, this would only work for commands.

**Comment by HubbeKing** [comment]
This is now implemented and hopefully working.
