### ISSUE TITLE
Connecting to multiple servers causes all bots to have the same config?

### ISSUE THREAD

**Issue by StarlitGhost** [DesertBot/DesertBot-old#23]
Whether starting from command line with -c server1 server2 or calling !connect

Causes all kinds of fun bugs, !quitfrom not working, !nick changing the nick on a different server, the admins list getting shared across all instances...

I've been trying to track this down but I'm giving up for now.

**Comment by HubbeKing** [comment]
Looked over the ConnectionHandling module, at it looks correct as far as I can tell, so I think the problem might be in the Factory, BotHandler or Config classes.

**Comment by HubbeKing** [comment]
Either that, or the parser in start.py is wrong, or passing it to the BotHandler is messing with it somehow.

**Comment by HubbeKing** [comment]
Preliminary testing shows that config objects are correct in the bothandler.

**Comment by HubbeKing** [comment]
What is happening, is that all commands are being sent to the first created bot instance, no matter where they were intended to go.

**Comment by HubbeKing** [comment]
Further testing shows that even the BotFactories are getting the correct configs, so it is unlikely the config handling is at fault.

**Comment by HubbeKing** [comment]
The problem was that we were hooking a bot reference onto each module, and since each bot instance uses the same module objects, just stores references to them in separate dicts, modules did not actually know which bot they were attached to.

**Comment by HubbeKing** [comment]
"Fixed" it by not doing that anymore, and instead tying a bot reference to each IRCMessage, and also passing the bot reference from moduleHandler to modules only in the onModuleLoaded and onModuleUnloaded functions.

**Comment by HubbeKing** [comment]
We need a better way of doing this IMO, which is why I'm leaving this issue open.

**Comment by HubbeKing** [comment]
Eh, this is solved, it works, we can think of a better way to do this for the inevitable 2.0 rewrite.
