### ISSUE TITLE
Module API for DesertBot 0.6

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#25]
I initially reopened our first issue for this, but I thought it might get messy if we start discussing two different APIs in the same issue.

These are the major things that are changing along with my proposal for the new API:
- A different module loading system. Since we're no longer using Twisted we can't rely on `twisted.plugin` for module loading anymore. Therefore I propose that we go with Python's built-in `importlib`. It's simple and we know how it works. One of our biggest problems with DesertBot < 0.6 was poor understanding of the framework we were using. By using something that we've all worked with before we can hopefully write a better API. Of course, we could always switch to a different module loading system in the future once we've got everything working. But for now I think it would be wise to keep things simple.
- A different class hierarchy. In the past we had a handler that kept track of different bots. Every bot had its own module handler. This was poor design and caused us to load a lot of things more than needed. It also caused us a lot of pain with a certain bug (that we are sadly all familiar with). This has to be done differently. I've already gone ahead and started a basic implementation of the new hierarchy. Rather than having multiple bots and a handler, I've gone and made one bot that keeps track of all its server connections. These classes, named respectively `DesertBot` and `DesertBotConnection` will be our foundation, of course with everyone's approval. We will link our module handler to the `DesertBot` instance. To keep track of what messages belong to which servers, we will keep a server field in our message class.
- As far as module types go, as discussed before in #8, I think we can keep that all the same, though it would be a good idea to look into an action system.

**Comment by ElementalAlchemist** [comment]
- Before switching to `twisted.plugin` for txircd, I used `imp`, which appears to be deprecated for `importlib`.  It's simple (a little basic, though) but effective.
- :thumbsup: on that second point.
- I'm not sure that all the types are required in combination with an action system (as I've mentioned before), but feel free to take it slowly--I often iterate over APIs two or three times before I start being happy with them.
