### ISSUE TITLE
Language and framework

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#3]
Considering the experience all three of us have, I would like to suggest Python and Twisted.

**Comment by HubbeKing** [comment]
+1 on that. As much as I'd love going with python 3, it's just too much work doing it all from scratch.

**Comment by Heufneutje** [comment]
Yeah. We'll just have to wait for Twisted to be compatible with Python 2 and try to use unicode everywhere from the start as best as we can.

**Comment by StarlitGhost** [comment]
This one is fairly obvious, I agree Python 2 and Twisted would be our best options.
