### ISSUE TITLE
Cross-server messaging

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#5]
Add the ability for the bot to send messages between two servers.

**Comment by Heufneutje** [comment]
I'm gonna toss up an idea for this since it popped into my head. PyHeufyBot passes a reference to the bot handler when he creates a factory. Since the bot handler knows what server connections exist, it could allow for cross-server messages.

**Comment by HubbeKing** [comment]
Hubbot does something very similar. Keeps references to the factories in the bothandler. As DesertBot is set up now, each Bot would know what Factory spawned it, so we could easily make every bot aware of the other bots currently running, I think.

**Comment by HubbeKing** [comment]
I'm thinking we should move the bothandler.py file out of the desertbot folder, and combine it with the start.py file. At the moment, it's a bit wonky to have start.py handle some of the argument parsing and bothandler.py do the rest of it. It'd be neater to have one file handle all of it.

**Comment by HubbeKing** [comment]
Also, cross-server messaging could be a module/plugin. Allow you to send commands to other servers, like tells and whatnot.

**Comment by Heufneutje** [comment]
Cross-server messaging should be a module, yes. Decided to move the disussion about the file architecture into its own issue, since this is an odd place for it.

**Comment by Heufneutje** [comment]
This issue should still be doable since we have a client pool we can hook into with Pydle.
