### ISSUE TITLE
Configuration handling

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#6]
I saw Hubbe already made a start with this so I think a discussion on this is needed. The way it currently is, a dictionary is read from YAML and values are being read from it. If we keep the way this currently works, we have to run a check to make sure all keys we're reading are present. If we don't, we're going to end up with a bunch of KeyErrors and/or unexpected behavior.

Another option would be to read a value with a default like PyHeufyBot does, but I kinda prefer the way Hubbe did it. We just need that check to happen. A Config class would be a good idea in this case I think.

**Comment by HubbeKing** [comment]
I actually had a bit of an idea. Why even have multiple config files? Since you can easily cause yaml to output dicts within dicts by indenting properly, we could store all the config stuff in one file. So we'd get one dict of useful config stuff per server, all stored in a dict, which we read from a yaml file. If you get what I mean...

**Comment by HubbeKing** [comment]
So it'd be like...
server1:
    nickname = butt

server2:
    nickname = butt

**Comment by HubbeKing** [comment]
Except that comments don't accept indenting, apparently. -.-

**Comment by Heufneutje** [comment]
I think separating it would be better. That way you could define global settings and every server config can override these.

**Comment by HubbeKing** [comment]
That is actually a better idea, yeah.

**Comment by Heufneutje** [comment]
I think @HubbeKing has implemented this for the most part. The only thing that's still missing is a global config file.

**Comment by HubbeKing** [comment]
Still needs some checks in the Config class to make sure the config files are accurate.

**Comment by StarlitGhost** [comment]
It looks good to me so far (just realised I hadn't commented on this one)

**Comment by Heufneutje** [comment]
Had another idea as far as startup and config loading goes. I vote for making the server command line parameter optional. If none are specified, we could scan the config folder and load all the YAML files that classify as a config file. We could also specify a flag in these config files that informs the bot whether or not to connect to that server on startup, or to just save the config for later use. Of course, you could always override this flag by using the command line parameter.

**Comment by HubbeKing** [comment]
Config handling is a bit of a mess at the moment. You've specified a global.yaml example file, so I assume you're thinking of using the same nickname across all bots and using server yaml files just for server, port and channel info?

**Comment by Heufneutje** [comment]
Yeah. Global configs can also have the same bot admins, command prefix and things like that.

**Comment by HubbeKing** [comment]
The rest of the bot currently assumes all it's Config stuff is in the same object, though. If we're gonna have globals in a separate one, we're gonna have to change that. Not to mention some architecture stuff, since each Bot currently only gets one Config object passed to it.

**Comment by HubbeKing** [comment]
Since we're joining the gobalconfig dict with the serverconfig dict using update, could we not use the globalConfig yaml file to store defaults? Or does update not... update values for keys already present?

**Comment by Heufneutje** [comment]
Update will update values for keys that are already present. And yes, we will put default values in the global config. That however does not guarantee that those values will be there at all times. The file could be modified. So we still need to make sure that the Config class adds the values that are missing.

(I don't want it to write these into the config file by the way, as writing to config files could cause all kinds of problems)

**Comment by HubbeKing** [comment]
So it might be a good idea to have nickname and stuff like that in defaultValues in the Config class aswell, then.

**Comment by Heufneutje** [comment]
We could. However, I think there should be a difference between default values and required values.
