### ISSUE TITLE
Bot admins should match on their full user string

### ISSUE THREAD

**Issue by Heufneutje** [DesertBot/DesertBot-old#7]
This is currently defined in the config as just a nickname, which is potentially insecure. By matching on `nickname!username@hostname`, we can make sure that someone really is who they say they are.

**Comment by HubbeKing** [comment]
Might be good. It becomes a bit trickier to add admins, and sometimes hostnames change. (Like when I'm here at home for summer)

**Comment by Heufneutje** [comment]
Well, DesertBus doesn't allow you to send messages unless you're identified if you're using a registered nick. So there we could just set it to `hubbeking!.*@.*`. I was more thinking in general.

**Comment by StarlitGhost** [comment]
Yeah, hostmasks with wildcard support seems like the best idea here.

**Comment by Heufneutje** [comment]
This is also easy to implement seeing as the IRCUser class already has a method that gives you the full user string.

**Comment by ElementalAlchemist** [comment]
Hostmask is perhaps a good idea. If you think you need extra security, a layer of password protection can't hurt.

**Comment by Heufneutje** [comment]
We could. I had one for old HeufyBot. It didn't really work too well and it was kind of a hassle though. If we do it again, we need to come up with a good way to do it.

**Comment by HubbeKing** [comment]
Full userstring matching is implemented already, someone just needs to finish the actual loading/saving/adding/removing of admins to/from JSON in the admin module.

**Comment by StarlitGhost** [comment]
This is implemented as of 5462380bc4d2b62db33f8c60ddf95075223f303d

The file creation doesn't work if there are no admins, as no one can use a command that would cause that code to execute.
Perhaps if there are no admins it should default to allowing anyone? Then when someone sets themselves as admin it would go to normal behaviour.
I made a new issue with this, #19
